# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7320192f4781c263ba1533efa9ef62f018f10b85be6e0a658edce01e115dc26b9f14adade114c799f4299d054a3d159bcc2747a1cfa267f2e1db973d16447b11

test:
  secret_key_base: 1466589e8b5e388e264867fa6daa30739e67e2a8a7a4d9d07bb3bd3089f789f185859880a0a035aee140347feaa9a59739cbb7267686326b94a29ef7291621e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
